version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "ninja_xia_server"
    restart: always
    depends_on:
      - mysql
      - redis
    volumes:
      - ./docker_settings.py:/NinjaXia/backend/ninja_xia/settings.py
      - ninja_xia_static:/NinjaXia/backend/static
    networks:
      - ninja_xia_network
    command:
      - bash
      - -c
      - |
        wait-for-it -s ninja_xia_mysql:3306 -s ninja_xia_redis:6379 -t 300
        python backend/manage.py makemigrations
        python backend/manage.py migrate
        uwsgi --ini docker_uwsgi.ini

  mysql:
    image: mysql:8.0.29
    ports:
      - "3306:3306"
    container_name: "ninja_xia_mysql"
    restart: always
    environment:
      MYSQL_DATABASE: ninja_xia
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - /var/lib/mysql
    networks:
      - ninja_xia_network
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1

  redis:
    image: redis:6.2.7
    ports:
      - "6379:6379"
    container_name: "ninja_xia_redis"
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/lib/redis
    networks:
      - ninja_xia_network

  nginx:
    image: nginx
    ports:
      - "8000:80"
    container_name: "ninja_xia_nginx"
    restart: always
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ninja_xia_static:/www/ninja_xia/static
    networks:
      - ninja_xia_network


networks:
  ninja_xia_network:

volumes:
  ninja_xia_static:
